config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :comics do
  member do
    get :toggle_status
  end
end

resources :blogs, only: [:edit, :create, :new, :update, :destroy]

root to: 'pages#home'

get'/cast', to: 'pages#cast'

get '/author', to: 'pages#author'

get '/news', to: 'pages#news'

get '/archive', to: 'pages#archive'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comic.rb
class Comic < ApplicationRecord
  def comic_order
    if comic.order == nil
      comic.order = comic.last.order + 1
    end
    comic.order
  end

#file uploading via CarrierWave
mount_uploader :thumb_image, ComicUploader
mount_uploader :main_image, ComicUploader

end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

   access all: [:show ], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

   layout "application"

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(comic_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to archive_path, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_path, notice: 'Blog was successfully saved.' }
      else
        format.html { render :new }
      end
    end
    redirect_to root_path, notice: "Post has been updated."
  end

  def destroy
    @blog.destroy

		respond_to do |format|
			format.html { redirect_to root_path, notice: "Blog was removed"}
		end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def comic_params
    params.require(:comic).permit(:title,
                                  :body
                                  )
  end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
   before_action :set_comic, only: [:show, :edit, :update, :destroy, :toggle_status]
   
   access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

   layout "application"

  def show
    @comic = Comic.find(params[:id])
    @is_first = @comic == Comic.first ? 'true' : 'false'
    @is_last = @comic == Comic.last ? 'true' : 'false'

  end

  def index
    @comics = Comic.all.order('created_at desc')
  end 

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to archive_path, notice: 'Comic was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @comic.save
        format.html { redirect_to comic_path, notice: 'Comic was successfully saved.' }
      else
        format.html { render :new }
      end
    end
  end


  def toggle_status

      if @comic.status == nil
        @comic.status = "draft"
      elsif @comic.status == "draft"
        @comic.status == "published"
      elsif @comic.published?
        @comic.draft!
    end

    redirect_to blogs_url, notice: "Post has been updated."
  end

  def destroy
    @comic.destroy

		respond_to do |format|
			format.html { redirect_to root_path, notice: "Comic was removed"}
		end
  end

  private

  def set_comic
    @comic = Comic.find(params[:id])
  end

  def comic_params
    params.require(:comic).permit(:title,
                                  :id,
                                  :main_image,
                                  :thumb_image,
                                  :description,
                                  :status,
                                  :order
                                  )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @comic = Comic.last
    @is_first = 'false'
    @is_last = 'true'
    @blog = Blog.last
  end

  def author
  end

  def news
  end

  def cast
  end

  def archive
    @comics = Comic.all.order('created_at desc')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  	def copyright_generator
  		HarkerViewTool::Renderer.copywrite 'Peggy Dolaghan', 'All Rights Reserved'
  	end

    def nav_items
  		[
  		{
  			url: root_path,
  			title: "Latest"
  		},
  		{
  			url: cast_path,
  			title: "Cast"
  		},
  		{
  			url: author_path,
  			title: "Author"
  		},
  		{
  			url: archive_path,
  			title: "Archive"
  		}
  	]
  	end

    def active? path
		"active" if current_page? path
	  end


  	def nav_helper style, tag_type
  		nav_links = ''

  		nav_items.each do |item|
  			nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>"
  		end

  		nav_links.html_safe
  	end


end

app/helpers/comics_helper.rb
module ComicsHelper


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
  <%= form_with(model: blog, local: true) do |form| %>
    <% if blog.errors.any? %>
        <% blog.errors.full_messages.each do |error| %>
          <%= alert_generator error %>
        <% end %>
    <% end %>

    <div class="form-group">
      <%= form.text_field :title, id: :title,  class: 'form-control', placeholder: 'Title' %>
    </div>

    <div class="form-group">
      <%= form.text_area :body, id: :body,  class: 'form-control', placeholder: 'Body' %>
    </div>

      <div class="form-group">
        <%= form.submit 'Submit', class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 p-md-3">
  </div>

 </div>
</div>

<div class="container" >
  <div class="row">
          <div class="col-md-8 blog-main">
            <div class="container">
              <div class="row">
                <div class="col-md-9 p-md-3">
                 <h1>Edit Blog Post</h1>
            			<%= render 'form', blog: @blog %>
            			<%= link_to 'Show', @blog %> |
            			<%= link_to 'Back', blog_path %>
                </div>
              </div>
              </div>
          </div>
      </div>
</div>

app/views/blogs/new.html.erb
            <div class="col-md-8 blog-main">
              <div class="container">
                <div class="row">
                  <div class="col-md-9 p-md-3">
                   <h1>New Blog Post</h1>
              			<%= render 'form', blog: @blog %>
              			<%= link_to 'Show', @blog %> |
              			<%= link_to 'Back', root_path %>
                  </div>
                </div>
              </div>
            </div>
  

app/views/comics/_form.html.erb
<%= form_with(model: comic, local: true) do |form| %>
  <% if comic.errors.any? %>
      <% comic.errors.full_messages.each do |error| %>
        <%= alert_generator error %>
      <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :title,  class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, id: :description,  class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="form-group">
    <%= form.text_field :order, id: :order,  class: 'form-control', placeholder: 'Order' %>
  </div>

  <div class="form-group">
		  	<label class="btn btn-primary btn-block">
		  		Upload main image file <%= form.file_field :main_image, style: 'display:none;' %>
		  	</label>
  </div>

  <div class="form-group">
  <label class="btn btn-primary btn-block">
    Upload thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
  </label>
  </div>

  <div class="form-group">
	<%= form.radio_button :status, 'draft' %>
	<%= form.label :status, 'Draft' %>
	<%= form.radio_button :status, 'published' %>
	<%= form.label :status, 'Published' %>
  </div>

    <div class="form-group">
      <%= form.submit 'Submit', class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>

app/views/comics/edit.html.erb
<div class="row">
        <div class="col-md-8 blog-main">

           <h1>Editing Comic</h1>

			<%= render 'form', comic: @comic %>

			<%= link_to 'Show', @comic %> |
			<%= link_to 'Back', comic_path %>


        </div><!-- /.blog-main -->

        <%= render 'shared/sidebar' %>
    </div>

app/views/comics/index.html.erb
<h1> index </h1>

app/views/comics/new.html.erb
<div class="row">
        <div class="col-md-8 blog-main">

           <h1>Editing Comic</h1>

			<%= render 'form', comic: @comic %>

			<%= link_to 'Show', @comic %> |
			<%= link_to 'Home', root_path %>


        </div><!-- /.blog-main -->

        <%= render 'shared/sidebar' %>
    </div>

app/views/comics/show.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-left">

  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3 class="position-relative display-4 font-weight-normal m-md-2">
          <%= @comic.title %>
        </h3>
    </div>
      <div class="col-md-3 p-md-3 text-right" >

      </div>
   </div>
 </div>

    <div class="comic-panel-container position-relative overflow-hidden  m-md-3 text-center">

      <%= render "shared/navigation" %>

      <%= image_tag @comic.main_image, width: "95%", height: "1200px", alt: @comic.title, title: @comic.description %>

      <%= render "shared/navigation" %>

    </div>
    <hr>
    <div class="container">
      <div class="row">

      <div class="col-md-8">
        <div class="blog-post">
            <h2 class="blog-post-title large-font">Another blog post</h2>
            <p class="blog-post-meta small-font">December 23, 2013 by <a href="#">Jacob</a></p>
            <div class="small-font">
            <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
            <blockquote>
              <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </blockquote>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
            <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
          </div>
          </div><!-- /.blog-post -->
        </div>

      <div clas="col-md-4">
        <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>
        <br>
        <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad",class: "m-md-2" %>
      </div>
      </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A Porter's Tale</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <%= auto_discovery_link_tag(:atom, comics_url(format: "atom")) %>

  </head>

  <body>

    <div class="cover-container container-fluid">

      <%= render 'shared/navbar' %>

      <main role="main" class="inner cover">
        <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-left">

          <%= yield %>
        </div>
      </main>

      <%= render 'shared/footer' %>
  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1 class="cover-heading">Cover your page.</h1>
<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
<p class="lead">
  <a href="#" class="btn btn-lg btn-secondary">Learn more</a>

</p>

app/views/pages/archive.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Archives</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Start from the Begining</a>
        <a href="#" class="btn btn-secondary my-2">Latest</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <% @comics.each do |c| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
            <%= link_to image_tag(c.thumb_image, alt: c.title, class:"card-img-top"), comic_path(c.id) %>

              <h5 class="card-title"><%= link_to c.title, comic_path(c.id) %></h5>
              <p class="card-text"><%= c.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">


                   <button type="button" class="btn btn-sm btn-outline-secondary">
                       <%= link_to "Edit", edit_comic_path(c.id) %>
                   </button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                      <%= link_to "Delete", comic_path(c.id), method: :delete, data: {confirm: 'Delete Comic?'} %>
                  </button>
                </div>
                <% if c.status == 'published' %>
                <small class="text-muted">Published <%= distance_of_time_in_words(c.created_at, Time.now) %> Ago</small>
                <% elsif c.status == 'draft' %>
                  <small class="text-muted">Draft created at <%= distance_of_time_in_words(c.created_at, Time.now) %> Ago</small>
                <% else %>
                    <small class="text-muted">Created <%= distance_of_time_in_words(c.created_at, Time.now) %> Ago</small>
                <% end %>

              </div>
            </div>
          </div>
        </div>
        <%end%>
      </div>
  </main>

app/views/pages/author.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-left">

  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3 class="position-relative display-4 font-weight-normal m-md-2">
          About the Author:
        </h3>
    </div>

   </div>
 </div>

    <div class="comic-panel-container position-relative overflow-hidden  m-md-3 text-center">
      <div class="container">
        <div class="row">
          <div clas="col-md-12 text-center">
            <%= image_tag "https://via.placeholder.com/640x480",alt: "Author Picture", class: "m-md-2 align-center" %>
          </div>
        <div class="col-md-12">
          <div class="blog-post">
              <h2 class="blog-post-title large-font">Character Name</h2>
              <div class="small-font text-left">
              <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
              <blockquote>
                <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              </blockquote>
              <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
              <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            </div>
            </div>
          </div>


        </div>
    </div>
    </div>
    <hr>
  </div>

app/views/pages/cast.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-left">

  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3 class="position-relative display-4 font-weight-normal m-md-2">
          Cast
        </h3>
    </div>

   </div>
 </div>

    <div class="comic-panel-container position-relative overflow-hidden  m-md-3 text-center">
      <div class="container">
        <div class="row">

        <div class="col-md-7">
          <div class="blog-post">
              <h2 class="blog-post-title large-font">Character Name</h2>
              <div clas="col-md-4">
                <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>
              </div>
              <div class="small-font">
              <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
              <blockquote>
                <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              </blockquote>
              <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
              <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            </div>
            </div>
          </div>

        <div class="col-md-7">
          <div class="blog-post">
              <h2 class="blog-post-title large-font">Character Name</h2>
              <div clas="col-md-4">
                <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>
              </div>
              <div class="small-font">
              <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
              <blockquote>
                <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              </blockquote>
              <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
              <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            </div>
            </div>
          </div>

        <div class="col-md-7">
          <div class="blog-post">
              <h2 class="blog-post-title large-font">Character Name</h2>
              <div clas="col-md-4">
                <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>
              </div>
              <div class="small-font">
              <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
              <blockquote>
                <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              </blockquote>
              <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
              <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
            </div>
            </div>
          </div>


        </div>
    </div>
    </div>
    <hr>


</div>

app/views/pages/contact.html.erb
<h1 class="cover-heading">Contac</h1>
<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
<p class="lead">
  <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
</p>

app/views/pages/home.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-left">

  <!-- <div class="container">
    <div class="row">
      <div class="col-md-10 nav_background">
          <%= image_tag "break_background" %>

    </div>
      <div class="col-md-8 p-md-3 text-right nav_forground" >
        <h4> Latest * Cast * Archive * Author </h4>
      </div>
   </div>
 </div> -->
 <div class="container">
   <div class="row">
     <div class="col-md-9 p-md-3">
       <%= image_tag "break_background", size: "1070x400" %>

   </div>

  </div>
 </div>

    <div class="comic-panel-container position-relative overflow-hidden  m-md-3 text-center">

      <%= render "shared/navigation" %>
      <h4 class="position-relative font-weight-normal m-md-3 text-left">
        <%= @comic.title %>
      </h4>
      <%= image_tag @comic.main_image, width: "95%", height: "1200px", alt: @comic.title, title: @comic.description %>

      <%= render "shared/navigation" %>

    </div>

          <div class="col-md-12 plug_break">
              <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>

          </div>
    <hr>
     <%= render 'shared/blog' %>

      <div clas="col-md-4">
        <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad", class: "m-md-2" %>
        <br>
        <%= image_tag "https://via.placeholder.com/300x250",alt: "placeholder for ad", title: "placeholder for ad",class: "m-md-2" %>
      </div>
      </div>
  </div>

</div>

app/views/pages/news.html.erb
<h1 class="cover-heading">News</h1>
<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
<p class="lead">
  <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
</p>

app/views/shared/_admin_tools.html.erb
<% patreon_link = "http://www.patreon.com" %>

  <div class="d-flex justify-content-between align-items-center btn-group">

  <% if current_user && current_user.has_roles?(:site_admin) %>

      <%= link_to image_tag(
      "edit.png",
      size: "32x32",
      alt: "Edit"),  edit_comic_path(@comic.id)
      %>

      <%= link_to image_tag(
      "delete.png",
      size: "32x32",
      alt: "Delete"),
      comic_path(@comic.id), method: :delete, data: {confirm: 'Delete Comic?'}
      %>

      <%= link_to image_tag(
      "new.png",
      size: "32x32",
      alt: "New"),
      new_comic_path
      %>
    <% else %>


    <% end %>

  </div>

app/views/shared/_blog.html.erb
<div class="container">
  <div class="row">

  <div class="col-md-8">
    <div class="blog-post">
        <h2 class="blog-post-title large-font"><%= @blog.title %></h2>
        <% if current_user && current_user.has_roles?(:site_admin) %>
          <p><strong>  <%= link_to "New", new_blog_path %> |
            <%= link_to "Edit", edit_blog_path(@blog.id) %> |
            <%= link_to "Delete", blog_path(@blog.id), method: :delete, data: {confirm: "Delete Blog"} %>
          </p></strong>
        <% end %>
        <p class="blog-post-meta small-font"><%= distance_of_time_in_words_to_now(@blog.created_at) %> ago. <a href="#"> by Peggy</a></p>
        <div class="small-font">
        <p><%= @blog.body %></p>

      </div>
      </div><!-- /.blog-post -->
    </div>

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
	<div class="inner">
					<%= copyright_generator %>
	</div>
</footer>

app/views/shared/_navigation.html.erb
<div class="col-md-12">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center">

    <%= render "shared/comic_nav" %>

    <%= render "shared/admin_tools" %>

    <%= render "shared/share_nav" %>

    </div>
  </div>
</div>

app/views/shared/_share_nav.html.erb
<% title_for_url = @comic.title.gsub(" ", '%20') %>

<% twitter_link = "https://twitter.com/intent/tweet?text=#{@comic.title}&url=http%3A%2F%2Fwww.aporterstale.com%2Fcomic%2F#{@comic.id}&original_referer=https%3A%2F%2Ftwitter.com%2Fshare%3Furl%3Dhttp%3A%2F%2Fwww.aporterstale.com%2F#{@comic.id}%26text%3D#{title_for_url}%2523aporterstale"%>

<% facebook_link =
"https://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.aporterstale.com%2Fcomic%2F#{@comic.id}&t=#{title_for_url}"
%>

<div class="d-flex justify-content-between align-items-center btn-group">

		<%= link_to (fa_icon "rss"), comics_url(format: "atom"), class: "btn btn-sm share_button" %>

		<%= link_to (fa_icon "twitter"), twitter_link, class: "btn btn-sm share_button" %>

		<%= link_to (fa_icon "facebook"), facebook_link, class: "btn btn-sm share_button" %>

	</div>

app/views/shared/_sidebar.html.erb
<h1> sidebar </h1>